"""Mock Browser Provider。

该 provider 不启动真实浏览器，只返回稳定的 mock 响应，用于安全验证
API、Tool、Planning 与可观测链路。
"""

from __future__ import annotations

from typing import Any
from uuid import uuid4

from app.browser.providers.base import BaseBrowserProvider, BrowserProviderResult


class MockBrowserProvider(BaseBrowserProvider):
    """当前默认使用的稳定 mock provider。"""

    provider_name = "mock"

    async def create_session(self, *, metadata: dict[str, Any] | None = None) -> BrowserProviderResult:
        """返回 mock provider session id。"""

        return BrowserProviderResult(
            success=True,
            message="mock browser session created",
            data={"provider_session_id": f"mock-{uuid4()}", "metadata": metadata or {}},
        )

    async def close_session(self, *, provider_session_id: str | None = None) -> BrowserProviderResult:
        """返回 mock 关闭响应。"""

        return BrowserProviderResult(
            success=True,
            message="mock browser session closed",
            data={"provider_session_id": provider_session_id},
        )

    async def navigate(
        self,
        *,
        target: str | None,
        input_payload: dict[str, Any],
        session_metadata: dict[str, Any] | None = None,
    ) -> BrowserProviderResult:
        """返回 mock 导航响应。"""

        return self._success("navigate", target=target, input_payload=input_payload, session_metadata=session_metadata)

    async def click(
        self,
        *,
        target: str | None,
        input_payload: dict[str, Any],
        session_metadata: dict[str, Any] | None = None,
    ) -> BrowserProviderResult:
        """返回 mock 点击响应。"""

        return self._success("click", target=target, input_payload=input_payload, session_metadata=session_metadata)

    async def type_text(
        self,
        *,
        target: str | None,
        input_payload: dict[str, Any],
        session_metadata: dict[str, Any] | None = None,
    ) -> BrowserProviderResult:
        """返回 mock 输入文本响应。"""

        return self._success("type_text", target=target, input_payload=input_payload, session_metadata=session_metadata)

    async def scroll(
        self,
        *,
        target: str | None,
        input_payload: dict[str, Any],
        session_metadata: dict[str, Any] | None = None,
    ) -> BrowserProviderResult:
        """返回 mock 滚动响应。"""

        return self._success("scroll", target=target, input_payload=input_payload, session_metadata=session_metadata)

    async def screenshot(
        self,
        *,
        target: str | None,
        input_payload: dict[str, Any],
        session_metadata: dict[str, Any] | None = None,
    ) -> BrowserProviderResult:
        """返回 mock 截图引用。"""

        result = self._success("screenshot", target=target, input_payload=input_payload, session_metadata=session_metadata)
        result.data["screenshot"] = "mock://browser/screenshot.png"
        result.data["screenshot_path"] = "mock://browser/screenshot.png"
        return result

    async def get_page_content(
        self,
        *,
        target: str | None,
        input_payload: dict[str, Any],
        session_metadata: dict[str, Any] | None = None,
    ) -> BrowserProviderResult:
        """返回稳定的 mock 页面文本。"""

        result = self._success("get_page_content", target=target, input_payload=input_payload, session_metadata=session_metadata)
        result.data["content"] = "Mock page content generated by MockBrowserProvider."
        return result

    def _success(
        self,
        action_type: str,
        *,
        target: str | None,
        input_payload: dict[str, Any],
        session_metadata: dict[str, Any] | None,
    ) -> BrowserProviderResult:
        """构造稳定的动作成功 payload。"""

        return BrowserProviderResult(
            success=True,
            message=f"mock browser {action_type} success",
            data={
                "action_type": action_type,
                "target": target,
                "target_url": target if action_type == "navigate" else None,
                "selector": input_payload.get("selector") or (target if action_type in {"click", "type_text"} else None),
                "input_payload": input_payload,
                "provider": self.provider_name,
                "page_title": "Mock Browser Page",
                "provider_session_metadata": session_metadata or {},
            },
        )
