"""Commercial operations documentation checks."""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def test_commercial_operations_foundation_doc_covers_runtime_and_boundary() -> None:
    text = (ROOT / "docs/COMMERCIAL_OPERATIONS_FOUNDATION.md").read_text(encoding="utf-8")

    for marker in (
        "Phase 61A",
        "Phase 61B",
        "Phase 61C",
        "Phase 61D",
        "Phase 61E",
        "Phase 61F",
        "Phase 61G",
        "Phase 61H",
        "Phase 61I",
        "Phase 61J",
        "Phase 61K",
        "Phase 61L",
        "Phase 61M",
        "Phase 61N",
        "Phase 61O",
        "Phase 61P",
        "Phase 61Q",
        "Phase 61R",
        "Phase 61S",
        "Phase 61T",
        "Phase 61U",
        "Phase 61V",
        "Phase 61W",
        "Phase 61X",
        "Phase 61Y",
        "Phase 61Z",
        "Phase 62A",
        "Phase 62B",
        "Phase 62C",
        "Phase 62D",
        "Phase 62E",
        "Phase 62F",
        "Phase 62G",
        "Phase 62H",
        "Phase 62J",
        "Phase 65A",
        "Phase 65B",
        "Phase 66A",
        "Phase 62Y",
        "commercial_operations",
        "commercial_operation_links",
        "commercial_operation_approvals",
        "commercial_operation_dry_runs",
        "commercial_operation_content_drafts",
        "commercial_operation_asset_requests",
        "commercial_operation_comfyui_handoffs",
        "commercial_operation_comfyui_preflights",
        "commercial_operation_comfyui_adapter_configs",
        "commercial_operation_comfyui_job_requests",
        "commercial_operation_comfyui_execution_plans",
        "commercial_operation_comfyui_connection_probes",
        "commercial_operation_comfyui_adapter_dispatches",
        "commercial_operation_comfyui_runtime_gates",
        "commercial_operation_comfyui_runtime_dry_runs",
        "commercial_operation_comfyui_runtime_activations",
        "comfyui_runtime_diagnostic_snapshots",
        "comfyui_runtime_config_change_requests",
        "comfyui_runtime_manual_apply_evidence",
        "comfyui_runtime_post_manual_readiness_checks",
        "comfyui_runtime_guarded_probe_executions",
        "commercial_operation_deliverables",
        "commercial_operation_execution_requests",
        "commercial_operation_execution_runs",
        "commercial_operation_results",
        "commercial_operation_monitoring_observations",
        "commercial_operation_optimization_decisions",
        "commercial_operation_evidence_snapshots",
        "CommercialOperationService",
        "CommercialOperationService.get_operation_loop_summary",
        "CommercialOperationLink",
        "CommercialOperationApproval",
        "CommercialOperationDryRun",
        "CommercialOperationContentDraft",
        "CommercialOperationAssetRequest",
        "CommercialOperationComfyUIHandoff",
        "CommercialOperationComfyUIPreflight",
        "CommercialOperationComfyUIAdapterConfig",
        "CommercialOperationComfyUIJobRequest",
        "CommercialOperationComfyUIExecutionPlan",
        "CommercialOperationComfyUIConnectionProbe",
        "CommercialOperationComfyUIAdapterDispatch",
        "CommercialOperationComfyUIRuntimeGate",
        "CommercialOperationComfyUIRuntimeDryRun",
        "CommercialOperationComfyUIRuntimeActivation",
        "ComfyUIRuntimeDiagnosticSnapshot",
        "ComfyUIRuntimeConfigChangeRequest",
        "ComfyUIRuntimeManualApplyEvidence",
        "ComfyUIRuntimePostManualReadinessCheck",
        "ComfyUIRuntimeGuardedProbeExecution",
        "CommercialOperationDeliverable",
        "CommercialOperationExecutionRequest",
        "CommercialOperationExecutionRun",
        "CommercialOperationResult",
        "CommercialOperationMonitoringObservation",
        "CommercialOperationOptimizationDecision",
        "CommercialOperationEvidenceSnapshot",
        "CommercialOperationLoopSummaryResponse",
        "CommercialOperationLoopStageResponse",
        "ComfyUIRuntimeService",
        "/api/v1/commercial-operations",
        "/api/v1/commercial-operations/{operation_id}/operation-loop",
        "/api/v1/commercial-operations/{operation_id}/links",
        "/api/v1/commercial-operations/{operation_id}/approvals",
        "/api/v1/commercial-operations/{operation_id}/dry-runs",
        "/api/v1/commercial-operations/{operation_id}/content-drafts",
        "/api/v1/commercial-operations/{operation_id}/content-drafts/generate-rag",
        "/api/v1/commercial-operations/{operation_id}/asset-requests",
        "/api/v1/commercial-operations/{operation_id}/asset-requests/generate-rag",
        "/api/v1/commercial-operations/{operation_id}/comfyui-handoffs",
        "/api/v1/commercial-operations/{operation_id}/comfyui-preflights",
        "/api/v1/commercial-operations/{operation_id}/comfyui-adapter-configs",
        "/api/v1/commercial-operations/{operation_id}/comfyui-job-requests",
        "/api/v1/commercial-operations/{operation_id}/comfyui-execution-plans",
        "/api/v1/commercial-operations/{operation_id}/comfyui-connection-probes",
        "/api/v1/commercial-operations/{operation_id}/comfyui-adapter-dispatches",
        "/api/v1/commercial-operations/{operation_id}/comfyui-runtime-gates",
        "/api/v1/commercial-operations/{operation_id}/comfyui-runtime-dry-runs",
        "/api/v1/commercial-operations/{operation_id}/comfyui-runtime-activations",
        "/api/v1/comfyui-runtime/health",
        "/api/v1/comfyui-runtime/capabilities",
        "/api/v1/comfyui-runtime/diagnostics",
        "/api/v1/comfyui-runtime/maintenance-runbook",
        "/api/v1/comfyui-runtime/diagnostic-snapshots",
        "/api/v1/comfyui-runtime/config-change-requests",
        "/api/v1/comfyui-runtime/manual-apply-evidence",
        "/api/v1/comfyui-runtime/post-manual-readiness-checks",
        "/api/v1/comfyui-runtime/guarded-probe-executions",
        "/api/v1/comfyui-runtime/prompt-jobs",
        "/api/v1/comfyui-runtime/video-resource-plans",
        "/api/v1/comfyui-runtime/prompt-jobs/{prompt_id}/history",
        "/api/v1/comfyui-runtime/queue",
        "/api/v1/commercial-operations/{operation_id}/comfyui-adapter-dispatches/{adapter_dispatch_id}/submit-runtime",
        "/api/v1/commercial-operations/{operation_id}/comfyui-adapter-dispatches/{adapter_dispatch_id}/refresh-runtime",
        "runtime_prompt_id",
        "runtime_outputs",
        "admission_status",
        "should_submit_now",
        "selected_endpoint",
        "endpoint_plans",
        "selected_gpu",
        "runtime_base_url",
        "COMFYUI_VIDEO_GPU_ENDPOINTS",
        "COMFYUI_RUNTIME_PROMPT_SUBMISSION_ENABLED",
        "COMFYUI_RUNTIME_ALLOWED_EXECUTION_PATHS",
        "/api/v1/commercial-operations/{operation_id}/deliverables",
        "/api/v1/commercial-operations/{operation_id}/execution-requests",
        "/api/v1/commercial-operations/{operation_id}/execution-runs",
        "/api/v1/commercial-operations/{operation_id}/results",
        "/api/v1/commercial-operations/{operation_id}/monitoring-observations",
        "/api/v1/commercial-operations/{operation_id}/optimization-decisions",
        "/api/v1/commercial-operations/{operation_id}/evidence-snapshots",
        "/api/v1/commercial-operations/{operation_id}/evidence-snapshots/generate-rag",
        "Admin Dashboard",
        "Admin Dashboard ComfyUI page",
        "?page=comfyui-operations",
        "Evidence",
        "handoff",
        "Approval",
        "Dry-Run",
        "Content Draft",
        "Asset Request",
        "ComfyUI Handoff",
        "ComfyUI Preflight",
        "ComfyUI Adapter Config",
        "ComfyUI Job Requests",
        "ComfyUI Execution Plans",
        "ComfyUI Connection Probes",
        "ComfyUI Adapter Dispatches",
        "ComfyUI Runtime Gates",
        "ComfyUI Runtime Dry-Runs",
        "ComfyUI Runtime Activations",
        "ComfyUI Runtime Adapter Contract",
        "ComfyUI Guarded Read-Only Probe",
        "ComfyUI Runtime Diagnostics",
        "ComfyUI Runtime Diagnostic Snapshots",
        "ComfyUI Runtime Maintenance Runbook",
        "ComfyUI Runtime Configuration Change Requests",
        "ComfyUI Runtime Manual Apply Evidence",
        "ComfyUI Runtime Post-Manual Readiness Checks",
        "ComfyUI Runtime Guarded Probe Execution Audit",
        "ComfyUI Video Resource Line",
        "configuration change requests",
        "manual apply evidence",
        "post-manual readiness",
        "config_mutation_performed",
        "api_config_mutation_performed",
        "guarded_probe_ready",
        "health_probe_executed",
        "probe_result_status",
        "Deliverable",
        "Execution Request",
        "Execution Run",
        "Result",
        "Monitoring Observation",
        "Optimization Decision",
        "Evidence Snapshot",
        "Commercial Operation Loop Protocol",
        "OpenClaw / Playwright customer-machine execution",
        "Output Library",
        "source_type=commercial_operation",
        "does not publish",
        "does not execute OpenClaw actions",
        "does not run ComfyUI jobs",
        "does not bypass approval",
    ):
        assert marker in text


def test_recovery_docs_point_to_phase_62j_comfyui_runtime_guarded_probe_execution() -> None:
    for relative in (
        "docs/PHASE_INDEX.md",
        "docs/CURRENT_NEXT_PHASE.md",
        "docs/PROJECT_STATUS.md",
        "docs/PROJECT_OVERVIEW.md",
        "docs/CURRENT_RUNTIME.md",
        "docs/en/PROJECT_STATUS.md",
        "docs/zh/PROJECT_STATUS.md",
        "docs/en/API_REFERENCE.md",
        "docs/zh/API_REFERENCE.md",
    ):
        text = (ROOT / relative).read_text(encoding="utf-8")
        assert "Phase 62J" in text or "62J" in text, relative
        assert "Guarded Probe Execution" in text or "guarded probe" in text or "guarded-probe" in text, relative
        assert "Phase 62H" in text or "62H" in text, relative
        assert "ComfyUI Runtime Post-Manual Readiness Checks" in text or "post-manual readiness" in text, relative
        assert "/comfyui-runtime/health" in text, relative
        assert "/comfyui-runtime/capabilities" in text, relative
        assert "/comfyui-runtime/diagnostics" in text, relative
        assert "/comfyui-runtime/maintenance-runbook" in text, relative
        assert "/comfyui-runtime/config-change-requests" in text, relative
        assert "/comfyui-runtime/manual-apply-evidence" in text, relative
        assert "/comfyui-runtime/post-manual-readiness-checks" in text, relative
        assert "/comfyui-runtime/guarded-probe-executions" in text, relative
        assert "/comfyui-runtime/diagnostic-snapshots" in text, relative
        assert "/comfyui-runtime/video-resource-plans" in text, relative
        assert "api_config_mutation_performed" in text or "manual_config_applied" in text, relative
        assert "guarded_probe_ready" in text or "health_probe_executed" in text, relative
        assert "probe_result_status" in text or "external_request_attempted" in text, relative
