"""Generate the Phase 55 superseded PR decision report."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]


def load_inventory() -> list[dict[str, Any]]:
    payload = json.loads((ROOT / "release/reports/pr_chain_inventory.json").read_text(encoding="utf-8"))
    items = payload.get("items", [])
    if not isinstance(items, list):
        raise ValueError("pr_chain_inventory.json items must be a list")
    return items


def decision_for(item: dict[str, Any]) -> dict[str, Any]:
    pr = item.get("pr")
    phase = item.get("phase")
    if pr == 13:
        recommendation = "keep for review until RC accepted"
        reason = "Source of docs stabilization, render QA, and phase status cleanup."
    elif pr == 14:
        recommendation = "keep as smoke/preflight source until RC accepted"
        reason = "Source of Phase 53 release preflight and smoke matrix."
    else:
        recommendation = "supersede after RC accepted"
        reason = "Covered by the combined Phase 43-55 release candidate stack."
    return {
        "pr": pr,
        "phase": phase,
        "title": item.get("title"),
        "branch": item.get("branch"),
        "recommendation": recommendation,
        "reason": reason,
    }


def build_report() -> dict[str, Any]:
    decisions = [decision_for(item) for item in load_inventory()]
    decisions.append(
        {
            "pr": 15,
            "phase": "54",
            "title": "Phase 54 Integration Branch and PR Chain Reconciliation",
            "branch": "codex/phase-54-integration-branch-pr-chain-reconciliation",
            "recommendation": "keep as Phase 55 base",
            "reason": "Source of integration strategy, PR inventory, conflict detection, and drift checks.",
        }
    )
    return {
        "schema_version": "1.0",
        "phase": "55",
        "current_effective_phase": "55",
        "phase_56_status": "reverted / not active / excluded from RC",
        "active_pr": 16,
        "success": True,
        "decisions": decisions,
        "rule": "Do not close superseded PRs until the final RC PR is accepted or a manual phase-by-phase merge path is chosen.",
    }


def to_markdown(report: dict[str, Any]) -> str:
    lines = [
        "# Superseded PR Decision Report",
        "",
        "This report is generated by `scripts/generate_superseded_pr_report.py`.",
        "",
        "Current effective phase: Phase 55. PR #16 is the active RC readiness PR. Phase 56 was reverted and is not active or included in this RC decision.",
        "",
        "## Decision Summary",
        "",
        "| PR | Phase | Branch | Recommendation | Reason |",
        "| --- | --- | --- | --- | --- |",
    ]
    for item in report["decisions"]:
        lines.append(
            f"| #{item['pr']} | {item['phase']} | `{item['branch']}` | {item['recommendation']} | {item['reason']} |"
        )
    lines.extend(["", "## Rule", "", report["rule"], ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate superseded PR decision report.")
    parser.add_argument("--markdown-output", default="release/reports/superseded_prs.md")
    parser.add_argument("--json-output", default="")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    report = build_report()
    markdown_path = ROOT / args.markdown_output
    markdown_path.parent.mkdir(parents=True, exist_ok=True)
    markdown_path.write_text(to_markdown(report), encoding="utf-8")
    if args.json_output:
        json_path = ROOT / args.json_output
        json_path.parent.mkdir(parents=True, exist_ok=True)
        json_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
    if args.json:
        print(json.dumps(report, indent=2))
    else:
        print(f"PASS: superseded PR report written to {markdown_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
