"""验证 docs 与当前 runtime / OpenAPI 是否一致。"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


@dataclass(frozen=True, slots=True)
class CheckResult:
    """单项校验结果。"""

    level: str
    message: str


class DocsRuntimeVerifier:
    """Docs Runtime Verification 主类。"""

    def __init__(self, root: Path) -> None:
        self.root = root
        self.docs = root / "docs"
        self.results: list[CheckResult] = []

    def run(self) -> int:
        """执行所有校验并输出结果。"""

        self.check_required_docs()
        self.check_runtime_config()
        self.check_openapi_and_api_docs()
        self.check_project_overview()
        self.check_phase_status()
        self.print_results()
        return 1 if any(result.level == "ERROR" for result in self.results) else 0

    def pass_(self, message: str) -> None:
        self.results.append(CheckResult("PASS", message))

    def warning(self, message: str) -> None:
        self.results.append(CheckResult("WARNING", message))

    def error(self, message: str) -> None:
        self.results.append(CheckResult("ERROR", message))

    def read_text(self, relative_path: str) -> str:
        path = self.root / relative_path
        try:
            return path.read_text(encoding="utf-8")
        except FileNotFoundError:
            self.error(f"Missing file: {relative_path}")
            return ""

    def check_required_docs(self) -> None:
        """检查 Phase 10.5/11 docs 结构是否存在。"""

        required = [
            "docs/PROJECT_OVERVIEW.md",
            "docs/CURRENT_RUNTIME.md",
            "docs/zh/PROJECT_STATUS.md",
            "docs/zh/ARCHITECTURE.md",
            "docs/zh/API_REFERENCE.md",
            "docs/zh/DEPLOYMENT.md",
            "docs/zh/DEVELOPMENT_GUIDE.md",
            "docs/zh/DOCS_RUNTIME_VERIFICATION.md",
            "docs/en/PROJECT_STATUS.md",
            "docs/en/ARCHITECTURE.md",
            "docs/en/API_REFERENCE.md",
            "docs/en/DEPLOYMENT.md",
            "docs/en/DEVELOPMENT_GUIDE.md",
            "docs/en/DOCS_RUNTIME_VERIFICATION.md",
            "worker_client/main.py",
            "worker_client/config.py",
            "worker_client/registration.py",
            "worker_client/heartbeat.py",
            "worker_client/runtime.py",
            "worker_client/cli.py",
            "worker_client/worker_config.example.yaml",
            "worker_client/openclaw/provider.py",
            "worker_client/openclaw/mock_provider.py",
            "worker_client/openclaw/schemas.py",
            "worker_client/openclaw/runtime.py",
            "worker_client/browser_runtime/runtime.py",
            "worker_client/browser_runtime/session_manager.py",
            "worker_client/browser_runtime/schemas.py",
            "worker_client/browser_runtime/playwright_provider.py",
            "worker_client/runtime_manager.py",
            "worker_client/status.py",
            "worker_client/logging.py",
            "worker_client/local_api_client.py",
            "worker_client/desktop/README.md",
            "worker_client/desktop/placeholder.py",
            "worker_console/package.json",
            "worker_console/index.html",
            "worker_console/vite.config.ts",
            "worker_console/tailwind.config.ts",
            "worker_console/src/main.tsx",
            "worker_console/src/api/localWorkerClient.ts",
            "worker_console/src/api/browserRuntimeClient.ts",
            "worker_console/.env.example",
            "worker_console/README.md",
            "worker_console_desktop/package.json",
            "worker_console_desktop/index.html",
            "worker_console_desktop/vite.config.ts",
            "worker_console_desktop/tailwind.config.ts",
            "worker_console_desktop/src/main.tsx",
            "worker_console_desktop/src/api/localWorkerClient.ts",
            "worker_console_desktop/src/api/browserRuntimeClient.ts",
            "worker_console_desktop/src/settings.ts",
            "worker_console_desktop/src/desktopBridge.ts",
            "worker_console_desktop/settings.example.json",
            "worker_console_desktop/src-tauri/tauri.conf.json",
            "worker_console_desktop/src-tauri/src/main.rs",
            "worker_console_desktop/src-tauri/desktop-runtime.json",
            "worker_console_desktop/autostart/README.md",
            "worker_console_desktop/autostart/windows_registry_placeholder.md",
            "worker_console_desktop/autostart/mac_launch_agent_placeholder.md",
            "worker_console_desktop/.env.example",
            "worker_console_desktop/README.md",
            "docs/zh/WORKER_CLIENT_INSTALL.md",
            "docs/en/WORKER_CLIENT_INSTALL.md",
            "docs/zh/WORKER_CONSOLE.md",
            "docs/en/WORKER_CONSOLE.md",
            "docs/zh/REAL_CLIENT_WORKER_E2E.md",
            "docs/en/REAL_CLIENT_WORKER_E2E.md",
            "scripts/validate_real_client_worker_e2e.py",
            "packaging/windows_install_requirements.ps1",
            "packaging/windows_register_worker.ps1",
            "packaging/windows_start_worker.ps1",
            "packaging/windows_stop_worker.ps1",
            "packaging/mac_install_requirements.sh",
            "packaging/mac_register_worker.sh",
            "packaging/mac_start_worker.sh",
            "packaging/mac_stop_worker.sh",
            "app/openclaw/client.py",
            "app/openclaw/schemas.py",
            "app/browser/providers/remote_provider.py",
            "app/browser/services/browser_runtime_session_service.py",
            "app/browser/services/browser_runtime_observability_service.py",
            "app/models/browser_runtime.py",
            "app/schemas/browser_runtime.py",
            "app/schemas/browser_runtime_observability.py",
            "app/api/routes/browser_runtime.py",
            "app/models/conversation.py",
            "app/conversation/tool_router.py",
            "app/conversation/risk_policy.py",
            "app/conversation/repositories/conversation_repository.py",
            "app/conversation/services/approval_service.py",
            "app/conversation/services/playbook_service.py",
            "app/conversation/playbook_definitions.py",
            "app/conversation/services/conversation_service.py",
            "app/models/output_artifact.py",
            "app/models/task_run.py",
            "app/schemas/output_artifact.py",
            "app/schemas/task_run.py",
            "app/services/output_artifact_service.py",
            "app/services/artifact_export_service.py",
            "app/services/artifact_packaging_service.py",
            "app/services/artifact_retention_service.py",
            "app/task_orchestration/service.py",
            "app/task_orchestration/background_executor.py",
            "app/task_orchestration/retry_policy.py",
            "app/task_orchestration/recovery_service.py",
            "app/api/routes/output_artifacts.py",
            "app/api/routes/task_runs.py",
            "app/api/routes/task_scheduler.py",
            "app/schemas/conversation.py",
            "app/schemas/conversation_playbook.py",
            "app/api/routes/conversations.py",
            "app/api/routes/conversation_approvals.py",
            "app/api/routes/conversation_playbooks.py",
            "worker_console/src/api/conversationClient.ts",
            "worker_console/src/api/outputArtifactClient.ts",
            "worker_console/src/api/taskRunClient.ts",
            "worker_console_desktop/src/api/conversationClient.ts",
            "worker_console_desktop/src/api/outputArtifactClient.ts",
            "worker_console_desktop/src/api/taskRunClient.ts",
            "admin_dashboard/package.json",
            "admin_dashboard/index.html",
            "admin_dashboard/vite.config.ts",
            "admin_dashboard/tailwind.config.ts",
            "admin_dashboard/src/main.tsx",
            "admin_dashboard/src/styles.css",
            "admin_dashboard/src/api/client.ts",
            "admin_dashboard/src/api/conversationClient.ts",
            "admin_dashboard/src/api/outputArtifactClient.ts",
            "admin_dashboard/src/api/taskRunClient.ts",
            "admin_dashboard/.env.example",
            "admin_dashboard/README.md",
            "docs/zh/ADMIN_DASHBOARD.md",
            "docs/en/ADMIN_DASHBOARD.md",
        ]
        missing = [path for path in required if not (self.root / path).exists()]
        if missing:
            for path in missing:
                self.error(f"Missing required docs file: {path}")
        else:
            self.pass_("Required zh/en docs structure exists")

    def check_runtime_config(self) -> None:
        """检查 CURRENT_RUNTIME 与 Settings / docker-compose 默认值是否一致。"""

        from app.core.config import Settings

        settings = Settings()
        current_runtime = self.read_text("docs/CURRENT_RUNTIME.md")
        compose = self.read_text("docker-compose.yml")
        expected_values = {
            "LLM_PROVIDER": settings.llm_provider,
            "CORS_ALLOWED_ORIGINS": settings.cors_allowed_origins,
            "LOCAL_LLM_MODEL": settings.local_llm_model,
            "EMBEDDING_PROVIDER": settings.embedding_provider,
            "LOCAL_EMBEDDING_MODEL": settings.local_embedding_model,
            "RERANKER_PROVIDER": settings.reranker_provider,
            "DEFAULT_SEARCH_MODE": settings.default_search_mode,
            "EMBEDDING_DIMENSION": str(settings.embedding_dimension),
            "MAX_UPLOAD_FILE_SIZE_MB": str(settings.max_upload_file_size_mb),
            "UPLOAD_TEMP_DIR": settings.upload_temp_dir,
            "ALLOWED_FILE_TYPES": settings.allowed_file_types,
            "BROWSER_PROVIDER": settings.browser_provider,
            "BROWSER_TIMEOUT_SECONDS": str(settings.browser_timeout_seconds),
            "BROWSER_HEADLESS": str(settings.browser_headless),
            "BROWSER_TYPE": settings.browser_type,
            "BROWSER_VIEWPORT_WIDTH": str(settings.browser_viewport_width),
            "BROWSER_VIEWPORT_HEIGHT": str(settings.browser_viewport_height),
            "BROWSER_SCREENSHOT_DIR": settings.browser_screenshot_dir,
            "BROWSER_RUNTIME_SCREENSHOT_DIR": settings.browser_runtime_screenshot_dir,
            "BROWSER_RUNTIME_SNAPSHOT_DIR": settings.browser_runtime_snapshot_dir,
            "BROWSER_PROFILE_ROOT": settings.browser_profile_root,
            "BROWSER_PROFILE_LOCK_TIMEOUT_SECONDS": str(settings.browser_profile_lock_timeout_seconds),
            "BROWSER_PROFILE_BACKUP_ENABLED": str(settings.browser_profile_backup_enabled),
            "BROWSER_PROFILE_MAX_BACKUPS": str(settings.browser_profile_max_backups),
            "BROWSER_PROFILE_UNUSED_DAYS": str(settings.browser_profile_unused_days),
            "BROWSER_PROFILE_BACKUP_ROOT": settings.browser_profile_backup_root,
            "BROWSER_HUMAN_CONTROL_TIMEOUT_SECONDS": str(settings.browser_human_control_timeout_seconds),
            "BROWSER_UI_ACCESS_TIMEOUT_SECONDS": str(settings.browser_ui_access_timeout_seconds),
            "BROWSER_WORKER_AUTH_ENABLED": str(settings.browser_worker_auth_enabled),
            "BROWSER_WORKER_AUTH_STRICT": str(settings.browser_worker_auth_strict),
            "BROWSER_ALLOWED_DOMAINS": settings.browser_allowed_domains,
            "BROWSER_BLOCKED_DOMAINS": settings.browser_blocked_domains,
            "BROWSER_ALLOW_EXTERNAL_DOMAINS": str(settings.browser_allow_external_domains),
            "BROWSER_WORKER_DEFAULT_TIMEOUT_SECONDS": str(settings.browser_worker_default_timeout_seconds),
            "BROWSER_WORKER_RETRY_COUNT": str(settings.browser_worker_retry_count),
            "BROWSER_WORKER_DEFAULT_URL": settings.browser_worker_default_url,
            "BROWSER_WORKER_HEARTBEAT_TIMEOUT_SECONDS": str(settings.browser_worker_heartbeat_timeout_seconds),
            "BROWSER_WORKER_HEALTH_CHECK_INTERVAL_SECONDS": str(
                settings.browser_worker_health_check_interval_seconds
            ),
            "BROWSER_SESSION_TIMEOUT_SECONDS": str(settings.browser_session_timeout_seconds),
            "BROWSER_SESSION_CLEANUP_INTERVAL_SECONDS": str(settings.browser_session_cleanup_interval_seconds),
            "BROWSER_ACTION_TIMEOUT_SECONDS": str(settings.browser_action_timeout_seconds),
            "BROWSER_ACTION_RETRY_COUNT": str(settings.browser_action_retry_count),
            "BROWSER_ACTION_RETRY_BACKOFF_SECONDS": str(settings.browser_action_retry_backoff_seconds),
            "SCREENSHOT_RETENTION_DAYS": str(settings.screenshot_retention_days),
            "OPENCLAW_PROVIDER": settings.openclaw_provider,
            "OPENCLAW_ENABLED": str(settings.openclaw_enabled),
            "OPENCLAW_ACTION_TIMEOUT_SECONDS": str(settings.openclaw_action_timeout_seconds),
            "TASK_ORCHESTRATOR_ENABLED": str(settings.task_orchestrator_enabled),
            "TASK_ORCHESTRATOR_POLL_INTERVAL_SECONDS": str(settings.task_orchestrator_poll_interval_seconds),
            "TASK_ORCHESTRATOR_BATCH_SIZE": str(settings.task_orchestrator_batch_size),
            "TASK_RUN_DEFAULT_MAX_RETRIES": str(settings.task_run_default_max_retries),
            "TASK_SCHEDULER_NAME": settings.task_scheduler_name,
            "TASK_LEASE_SECONDS": str(settings.task_lease_seconds),
            "TASK_STUCK_TIMEOUT_SECONDS": str(settings.task_stuck_timeout_seconds),
            "TASK_SCHEDULER_RECOVERY_INTERVAL_SECONDS": str(settings.task_scheduler_recovery_interval_seconds),
            "OUTPUT_ARTIFACT_DIR": settings.output_artifact_dir,
            "OUTPUT_PACKAGE_DIR": settings.output_package_dir,
            "OUTPUT_EXPORT_DIR": settings.output_export_dir,
        }
        for key, value in expected_values.items():
            if key not in current_runtime or str(value) not in current_runtime:
                self.error(f"CURRENT_RUNTIME.md does not document {key}={value}")
            else:
                self.pass_(f"CURRENT_RUNTIME documents {key}={value}")
            if key not in compose:
                self.error(f"docker-compose.yml does not expose {key}")
        if "MAX_UPLOAD_FILE_SIZE_MB" in compose and "ALLOWED_FILE_TYPES" in compose:
            self.pass_("docker-compose.yml exposes upload runtime settings")

    def check_openapi_and_api_docs(self) -> None:
        """检查真实 OpenAPI 路径是否已写入 API_REFERENCE。"""

        from app.main import create_app

        app = create_app()
        openapi = app.openapi()
        paths = set(openapi.get("paths", {}).keys())
        zh_api = self.read_text("docs/zh/API_REFERENCE.md")
        en_api = self.read_text("docs/en/API_REFERENCE.md")
        required_paths = [
            "/api/v1/health",
            "/api/v1/llm/health",
            "/api/v1/llm/test",
            "/api/v1/rag/embedding/health",
            "/api/v1/rag/ingest",
            "/api/v1/rag/search",
            "/api/v1/rag/debug",
            "/api/v1/files/upload",
            "/api/v1/reranker/health",
            "/api/v1/agentic-rag/query",
            "/api/v1/tasks",
            "/api/v1/tasks/{task_id}/cancel",
            "/api/v1/tasks/{task_id}/retry",
            "/api/v1/tasks/{task_id}/events",
            "/api/v1/tasks/{task_id}/logs",
            "/api/v1/observability/summary",
            "/api/v1/tools",
            "/api/v1/tools/{tool_name}",
            "/api/v1/tools/{tool_name}/execute",
            "/api/v1/tool-calls",
            "/api/v1/memory/sessions",
            "/api/v1/memory/sessions/{session_id}",
            "/api/v1/memory/messages",
            "/api/v1/memory/messages/{session_id}",
            "/api/v1/memory/memories",
            "/api/v1/memory/memories/{memory_id}",
            "/api/v1/agents/registry",
            "/api/v1/multi-agent/runs",
            "/api/v1/multi-agent/runs/{run_id}",
            "/api/v1/multi-agent/runs/{run_id}/execute-chain",
            "/api/v1/multi-agent/runs/{run_id}/messages",
            "/api/v1/multi-agent/runs/{run_id}/handoffs",
            "/api/v1/plans",
            "/api/v1/plans/{plan_id}",
            "/api/v1/plans/{plan_id}/execute",
            "/api/v1/plans/{plan_id}/cancel",
            "/api/v1/plans/{plan_id}/steps",
            "/api/v1/plans/{plan_id}/reviews",
            "/api/v1/browser/sessions",
            "/api/v1/browser/sessions/{session_id}/close",
            "/api/v1/browser/profiles",
            "/api/v1/browser/profiles/recover-stale-locks",
            "/api/v1/browser/profiles/cleanup",
            "/api/v1/browser/profiles/health/summary",
            "/api/v1/browser/profiles/{profile_id}",
            "/api/v1/browser/profiles/{profile_id}/health-check",
            "/api/v1/browser/profiles/{profile_id}/backup",
            "/api/v1/browser/profiles/{profile_id}/backups",
            "/api/v1/browser/profiles/{profile_id}/restore",
            "/api/v1/browser/profiles/{profile_id}/usage-logs",
            "/api/v1/browser/profiles/{profile_id}/lock",
            "/api/v1/browser/profiles/{profile_id}/release",
            "/api/v1/browser/human-control/request",
            "/api/v1/browser/human-control",
            "/api/v1/browser/human-control/{control_session_id}",
            "/api/v1/browser/human-control/{control_session_id}/approve",
            "/api/v1/browser/human-control/{control_session_id}/start",
            "/api/v1/browser/human-control/{control_session_id}/complete",
            "/api/v1/browser/human-control/{control_session_id}/cancel",
            "/api/v1/browser/human-control/{control_session_id}/events",
            "/api/v1/browser/ui-access",
            "/api/v1/browser/ui-access/expire",
            "/api/v1/browser/ui-access/{access_session_id}",
            "/api/v1/browser/ui-access/{access_session_id}/revoke",
            "/api/v1/browser/ui-access/{access_session_id}/validate",
            "/api/v1/browser/security/audit-logs",
            "/api/v1/browser/security/policy/check",
            "/api/v1/browser/actions",
            "/api/v1/browser/actions/{session_id}",
            "/api/v1/browser/screenshot/{session_id}/{filename}",
            "/api/v1/browser/logs/{session_id}",
            "/api/v1/browser-runtime/sessions",
            "/api/v1/browser-runtime/sessions/{session_id}",
            "/api/v1/browser-runtime/sessions/{session_id}/navigate",
            "/api/v1/browser-runtime/sessions/{session_id}/screenshot",
            "/api/v1/browser-runtime/sessions/{session_id}/page",
            "/api/v1/browser-runtime/sessions/{session_id}/close",
            "/api/v1/browser-runtime/sessions/{session_id}/events",
            "/api/v1/browser-runtime/sessions/{session_id}/snapshots",
            "/api/v1/browser-runtime/sessions/{session_id}/replay",
            "/api/v1/browser-runtime/replays/{replay_id}",
            "/api/v1/browser-runtime/replays/{replay_id}/export",
            "/api/v1/browser-workers/register",
            "/api/v1/browser-workers/{worker_id}/heartbeat",
            "/api/v1/browser-workers/{worker_id}/rotate-secret",
            "/api/v1/browser-workers/{worker_id}/revoke",
            "/api/v1/browser-workers",
            "/api/v1/browser-workers/health/summary",
            "/api/v1/browser-workers/available",
            "/api/v1/browser-workers/{worker_id}/mark-offline",
            "/api/v1/browser-workers/cleanup-sessions",
            "/api/v1/browser-workers/{worker_id}/sessions",
            "/api/v1/browser-worker-runtime/health",
            "/api/v1/browser-worker-runtime/sessions",
            "/api/v1/browser-worker-runtime/actions",
            "/api/v1/browser-worker-runtime/sessions/{session_id}/close",
            "/api/v1/browser-worker-runtime/browser/session/create",
            "/api/v1/browser-worker-runtime/browser/session/{session_id}/navigate",
            "/api/v1/browser-worker-runtime/browser/session/{session_id}/screenshot",
            "/api/v1/browser-worker-runtime/browser/session/{session_id}/page",
            "/api/v1/browser-worker-runtime/browser/session/{session_id}/close",
            "/api/v1/browser-worker-runtime/human-control/start",
            "/api/v1/browser-worker-runtime/human-control/complete",
            "/api/v1/browser-worker-runtime/human-control/status/{session_id}",
            "/api/v1/browser-worker-runtime/ui-access/capabilities",
            "/api/v1/browser-worker-runtime/openclaw/health",
            "/api/v1/browser-worker-runtime/openclaw/capabilities",
            "/api/v1/browser-worker-runtime/openclaw/actions",
            "/api/v1/openclaw/health",
            "/api/v1/openclaw/capabilities",
            "/api/v1/openclaw/actions",
            "/api/v1/conversations",
            "/api/v1/conversations/{thread_id}",
            "/api/v1/conversations/{thread_id}/messages",
            "/api/v1/conversations/{thread_id}/events",
            "/api/v1/conversations/{thread_id}/approvals",
            "/api/v1/conversations/{thread_id}/run",
            "/api/v1/conversation-approvals/{approval_id}",
            "/api/v1/conversation-approvals/{approval_id}/approve",
            "/api/v1/conversation-approvals/{approval_id}/reject",
            "/api/v1/conversation-approvals/{approval_id}/cancel",
            "/api/v1/conversation-approvals/{approval_id}/execute",
            "/api/v1/conversation-playbooks",
            "/api/v1/conversation-playbooks/{playbook_id}",
            "/api/v1/conversation-playbooks/{playbook_id}/run",
            "/api/v1/conversation-playbook-runs",
            "/api/v1/conversation-playbook-runs/{run_id}",
            "/api/v1/conversation-playbook-runs/{run_id}/cancel",
            "/api/v1/output-artifacts",
            "/api/v1/output-artifacts/{artifact_id}",
            "/api/v1/output-artifacts/from-message/{message_id}",
            "/api/v1/output-artifacts/from-playbook-run/{run_id}",
            "/api/v1/output-artifacts/{artifact_id}/export",
            "/api/v1/output-artifacts/{artifact_id}/lineage",
            "/api/v1/output-artifacts/{artifact_id}/relationships",
            "/api/v1/output-artifacts/{artifact_id}/package",
            "/api/v1/output-artifacts/cleanup/preview",
            "/api/v1/task-runs",
            "/api/v1/task-runs/{task_run_id}",
            "/api/v1/task-runs/{task_run_id}/events",
            "/api/v1/task-runs/{task_run_id}/diagnostics",
            "/api/v1/task-runs/{task_run_id}/recover",
            "/api/v1/task-runs/{task_run_id}/retry",
            "/api/v1/task-runs/{task_run_id}/cancel",
            "/api/v1/task-runs/{task_run_id}/resume",
            "/api/v1/task-scheduler/health",
            "/api/v1/task-scheduler/scan",
            "/api/v1/browser/screenshots/cleanup",
            "/api/v1/documents",
            "/api/v1/rag/eval/runs",
        ]
        for path in required_paths:
            if path not in paths:
                self.error(f"OpenAPI path missing: {path}")
                continue
            self.pass_(f"OpenAPI contains {path}")
            if path not in zh_api:
                self.error(f"zh/API_REFERENCE.md does not document {path}")
            if path not in en_api:
                self.error(f"en/API_REFERENCE.md does not document {path}")
        for field in (
            "search_mode",
            "dense_top_k",
            "keyword_top_k",
            "final_top_k",
            "duplicate_strategy",
            "task_events",
            "task_logs",
            "duration_ms",
            "tool_call_logs",
            "tool_name",
            "tool_input",
            "tool_output",
            "conversation_sessions",
            "conversation_messages",
            "agent_memories",
            "memory_trace",
            "recent_messages_count",
            "retrieved_memories_count",
            "agent_runs",
            "agent_messages",
            "agent_handoffs",
            "AgentRegistry",
            "agents_involved",
            "handoff_trace",
            "plans",
            "plan_steps",
            "plan_reviews",
            "PlanStep",
            "PlanReview",
            "SimplePlannerAgent",
            "browser_sessions",
            "browser_actions",
            "browser_action_logs",
            "browser_tool",
            "BrowserProvider",
            "MockBrowserProvider",
            "PlaywrightBrowserProvider",
            "PlaywrightLocalProvider",
            "playwright_local",
            "BROWSER_PROVIDER",
            "BROWSER_TIMEOUT_SECONDS",
            "BROWSER_SCREENSHOT_DIR",
            "browser_id",
            "page_id",
            "provider_session_metadata",
            "selector",
            "target_url",
            "screenshot_path",
            "page_title",
            "get_page_content",
            "RemoteBrowserProvider",
            "BrowserWorkerClient",
            "browser_workers",
            "browser_worker_sessions",
            "browser_worker_actions",
            "remote_session_id",
            "remote_action_id",
            "BROWSER_WORKER_DEFAULT_TIMEOUT_SECONDS",
            "BROWSER_WORKER_RETRY_COUNT",
            "BROWSER_WORKER_DEFAULT_URL",
            "Real Browser Worker Service",
            "browser-worker",
            "worker/main.py",
            "worker/browser_worker/playwright_runtime.py",
            "http://browser-worker:9100",
            "WORKER_TIMEOUT_SECONDS",
            "WORKER_SCREENSHOT_DIR",
            "BrowserWorkerHealthService",
            "BrowserWorkerSelector",
            "BrowserSessionCleanupService",
            "ScreenshotCleanupService",
            "max_sessions",
            "active_sessions",
            "max_actions_per_minute",
            "current_load",
            "priority",
            "error_message",
            "last_seen",
            "retry_count",
            "max_retries",
            "BROWSER_WORKER_HEARTBEAT_TIMEOUT_SECONDS",
            "BROWSER_WORKER_HEALTH_CHECK_INTERVAL_SECONDS",
            "BROWSER_SESSION_TIMEOUT_SECONDS",
            "BROWSER_SESSION_CLEANUP_INTERVAL_SECONDS",
            "BROWSER_ACTION_TIMEOUT_SECONDS",
            "BROWSER_ACTION_RETRY_COUNT",
            "BROWSER_ACTION_RETRY_BACKOFF_SECONDS",
            "SCREENSHOT_RETENTION_DAYS",
            "BrowserProfileService",
            "browser_profiles",
            "profile_id",
            "profile_path",
            "persistent_context_enabled",
            "locked_by_session_id",
            "locked_at",
            "last_used_at",
            "launch_persistent_context",
            "BROWSER_PROFILE_ROOT",
            "BrowserProfileHealthService",
            "BrowserProfileBackupService",
            "BrowserProfileCleanupService",
            "browser_profile_usage_logs",
            "health_status",
            "last_health_check_at",
            "last_error",
            "usage_count",
            "corrupted_at",
            "backup_path",
            "last_backup_at",
            "recover-stale-locks",
            "health/summary",
            "BROWSER_PROFILE_LOCK_TIMEOUT_SECONDS",
            "BROWSER_PROFILE_BACKUP_ENABLED",
            "BROWSER_PROFILE_MAX_BACKUPS",
            "BROWSER_PROFILE_UNUSED_DAYS",
            "BROWSER_PROFILE_BACKUP_ROOT",
            "BrowserHumanControlService",
            "browser_human_control_sessions",
            "browser_human_control_events",
            "human_control_status",
            "human_control_session_id",
            "paused_at",
            "resumed_at",
            "request_human_control",
            "complete_human_control",
            "BROWSER_HUMAN_CONTROL_TIMEOUT_SECONDS",
            "BrowserUIAccessService",
            "browser_ui_access_sessions",
            "access_token_hash",
            "scopes",
            "one_time",
            "used_at",
            "revoked_reason",
            "client_ip",
            "user_agent",
            "remote_control_url",
            "live_view_url",
            "devtools_url",
            "create_ui_access",
            "revoke_ui_access",
            "BROWSER_UI_ACCESS_TIMEOUT_SECONDS",
            "BrowserWorkerAuthService",
            "BrowserActionPolicyService",
            "BrowserSecurityAuditLog",
            "browser_security_audit_logs",
            "worker_secret_hash",
            "api_key_hash",
            "last_auth_at",
            "auth_status",
            "allowed_actions",
            "allowed_domains",
            "worker_secret",
            "X-Worker-Signature",
            "X-Worker-Timestamp",
            "X-Worker-Nonce",
            "BROWSER_WORKER_AUTH_ENABLED",
            "BROWSER_WORKER_AUTH_STRICT",
            "BROWSER_ALLOWED_DOMAINS",
            "BROWSER_BLOCKED_DOMAINS",
            "BROWSER_ALLOW_EXTERNAL_DOMAINS",
            "worker_client",
            "worker_config.example.yaml",
            "worker_config.yaml",
            "worker_state.json",
            "python -m worker_client.cli register",
            "python -m worker_client.cli heartbeat",
            "python -m worker_client.cli serve",
            "python -m worker_client.cli start",
            "Customer Machine Worker Bootstrap",
            "registration flow",
            "heartbeat flow",
            "local worker runtime",
            "UI Access Placeholder",
            "WORKER_PROFILE_DIR",
            "OpenClaw Worker Adapter Foundation",
            "worker_client/openclaw",
            "BaseOpenClawProvider",
            "MockOpenClawProvider",
            "OpenClawRuntime",
            "OpenClawWorkerClient",
            "openclaw_tool",
            "openclaw_action_logs",
            "OPENCLAW_PROVIDER",
            "OPENCLAW_ENABLED",
            "OPENCLAW_ACTION_TIMEOUT_SECONDS",
            "Worker Runtime Manager",
            "worker_client/runtime_manager.py",
            "worker_client/status.py",
            "worker_client/logging.py",
            "worker_client/local_api_client.py",
            "worker_client/runtime_state/status.json",
            "worker_client/logs/worker.log",
            "/local/status",
            "/local/health",
            "/local/runtime/start",
            "/local/runtime/stop",
            "/local/runtime/restart",
            "/local/heartbeat/start",
            "/local/heartbeat/stop",
            "/local/logs",
            "Packaging Scripts",
            "packaging/windows_start_worker.ps1",
            "packaging/mac_start_worker.sh",
            "Worker Console Foundation",
            "Desktop Runtime Placeholder",
            "no GUI",
            "Worker Console GUI Foundation",
            "worker_console",
            "Vite",
            "React",
            "TypeScript",
            "Tailwind",
            "localWorkerClient.ts",
            "VITE_LOCAL_WORKER_API",
            "http://127.0.0.1:9100",
            "Runtime Control",
            "Worker API unreachable",
            "no exe / dmg",
            "no system tray",
            "Worker Console Desktop App Foundation",
            "worker_console_desktop",
            "Tauri",
            "src-tauri/tauri.conf.json",
            "npm run tauri dev",
            "http://127.0.0.1:9100/local/status",
            "Worker Runtime 未启动",
            "no auto update",
            "Worker Console System Tray & Desktop Runtime Foundation",
            "System Tray",
            "Minimize To Tray",
            "Tray Runtime Control",
            "Desktop Status Sync",
            "AutoStart Placeholder",
            "settings.example.json",
            "minimizeToTray",
            "refreshIntervalMs",
            "minimize_to_tray",
            "Show Console",
            "Hide Window",
            "Refresh Status",
            "Quit",
            "no formal installer",
            "no auto-update",
            "remote shell",
            "arbitrary shell",
            "Conversation Runtime Foundation",
            "conversation_threads",
            "conversation_events",
            "ConversationService",
            "run_conversation_turn",
            "message_received",
            "planning_started",
            "tool_called",
            "worker_action_started",
            "assistant_response",
            "Chat Panel Foundation",
            "Event Timeline",
            "polling",
            "WebSocket",
            "SSE",
            "Remote Browser Runtime Foundation",
            "browser_runtime_sessions",
            "BrowserRuntimeSessionService",
            "app/browser/providers/remote_provider.py",
            "worker_client/browser_runtime",
            "/browser/session/create",
            "/browser/session/{session_id}/navigate",
            "/browser/session/{session_id}/screenshot",
            "/browser/session/{session_id}/page",
            "/browser/session/{session_id}/close",
            "storage/browser_screenshots",
            "BROWSER_RUNTIME_SCREENSHOT_DIR",
            "Browser Sessions Panel",
            "playwright install chromium",
            "Browser Runtime Observability & Replay",
            "browser_runtime_events",
            "browser_runtime_snapshots",
            "browser_runtime_replays",
            "BrowserRuntimeObservabilityService",
            "Browser Runtime Timeline",
            "Browser Runtime Snapshots",
            "Browser Runtime Replay Metadata",
            "BROWSER_RUNTIME_SNAPSHOT_DIR",
            "storage/browser_runtime_snapshots",
            "page_snapshot_captured",
            "replay_requested",
            "metadata-only replay",
            "not live stream",
            "not VNC",
            "not DevTools",
            "Phase 35B",
            "Real Client Worker E2E Validation Plan",
            "validate_real_client_worker_e2e.py",
            "expected_worker_name",
            "SKIPPED",
            "real client worker not online",
            "do not expose port 9100 to the public internet",
            "Tailscale",
            "VPN",
            "Phase 36",
            "Admin Dashboard Foundation",
            "admin_dashboard",
            "VITE_AI_SERVER_API",
            "VITE_WORKSPACE_ID",
            "VITE_USER_ID",
            "workersApi",
            "browserRuntimeApi",
            "conversationsApi",
            "tasksApi",
            "openclawApi",
            "auditApi",
            "ragApi",
            "Overview",
            "Workers",
            "Browser Runtime",
            "Audit Logs",
            "RAG / Documents",
            "Settings",
            "read-only monitoring foundation",
            "no login UI",
            "no permission UI",
            "no publishing business flow",
            "no real social platform control",
            "Phase 37",
            "Conversation Runtime Frontend Integration",
            "admin_dashboard/src/api/conversationClient.ts",
            "createThread",
            "sendMessage",
            "runConversation",
            "listMessages",
            "listEvents",
            "Worker Console Chat Panel",
            "Desktop Chat Panel",
            "Polling Event Timeline",
            "AI Server unreachable",
            "CORS_ALLOWED_ORIGINS",
            "tauri://localhost",
            "not WebSocket",
            "not SSE",
            "not a full ChatGPT UI",
            "Phase 38",
            "Conversation Runtime Tool Execution Bridge",
            "ConversationToolRouter",
            "app/conversation/tool_router.py",
            "route_selected",
            "tool_execution_started",
            "tool_execution_completed",
            "tool_execution_failed",
            "agent_execution_started",
            "agent_execution_completed",
            "planning_execution_started",
            "planning_execution_completed",
            "bridge_fallback",
            "bridge_error",
            "route_name",
            "selected_tool",
            "events_created",
            "success",
            "summary",
            "result_metadata",
            "Browser Bridge",
            "OpenClaw mock bridge",
            "RAG bridge",
            "Content bridge",
            "Planning bridge",
            "not autonomous agent",
            "Phase 39",
            "Conversation Execution Review & Approval Flow",
            "conversation_approvals",
            "ConversationApprovalService",
            "ConversationRiskPolicy",
            "approval_required",
            "approval_created",
            "approval_approved",
            "approval_rejected",
            "approval_cancelled",
            "approval_executed",
            "execution_blocked_pending_approval",
            "execution_after_approval_started",
            "execution_after_approval_completed",
            "risk_level",
            "approval_status",
            "review_first",
            "auto_safe",
            "execute_after_approval",
            "pending approvals panel",
            "Tool Execution Gate",
            "not a full permission system",
            "conversation_playbooks",
            "conversation_playbook_runs",
            "playbook_name",
            "playbook_run_id",
            "current_step",
            "playbook_selected",
            "playbook_run_started",
            "playbook_step_started",
            "playbook_waiting_approval",
            "playbook_completed",
            "output_artifacts",
            "OutputArtifactService",
            "Output Library",
            "artifact_type",
            "source_type",
            "parent_artifact_id",
            "root_artifact_id",
            "source_task_run_id",
            "source_playbook_run_id",
            "source_conversation_id",
            "source_runtime_session_id",
            "artifact_role",
            "artifact_stage",
            "generated_by",
            "exportable",
            "retention_policy",
            "expires_at",
            "artifact_relationships",
            "relationship_type",
            "derived_from",
            "packaged_into",
            "exported_from",
            "ArtifactExportService",
            "ArtifactPackagingService",
            "ArtifactRetentionService",
            "Artifact Explorer",
            "lineage graph",
            "relationship graph",
            "bundle.zip",
            "storage/output_packages",
            "storage/output_exports",
            "retention preview",
            "production object storage platform",
            "content_draft",
            "rag_answer",
            "html_snapshot",
            "artifact_created",
            "artifact_exported",
            "artifact_deleted",
            "artifact_linked_to_playbook_run",
            "task_runs",
            "task_run_events",
            "TaskOrchestratorService",
            "BackgroundTaskExecutor",
            "TaskRetryPolicy",
            "execution_mode",
            "scheduled_at",
            "queued",
            "waiting_approval",
            "retrying",
            "task_run_id",
            "task_queued",
            "task_started",
            "task_retry_scheduled",
            "task_completed",
            "task_cancelled",
            "artifact linkage",
            "task_scheduler_state",
            "TaskRecoveryService",
            "lease_owner",
            "lease_token",
            "lease_expires_at",
            "heartbeat_at",
            "recovery_count",
            "last_recovered_at",
            "recovery_reason",
            "failure_category",
            "failure_reason",
            "recoverable",
            "suggested_action",
            "scheduler health",
            "stuck task recovery",
            "expired lease",
            "TASK_SCHEDULER_NAME",
            "TASK_LEASE_SECONDS",
            "TASK_STUCK_TIMEOUT_SECONDS",
            "TASK_SCHEDULER_RECOVERY_INTERVAL_SECONDS",
            "not Celery",
            "not Kubernetes",
            "Save as Artifact",
            "Export markdown",
            "not a full DAM",
            "S3",
            "MinIO",
        ):
            if field not in zh_api or field not in en_api:
                self.error(f"API_REFERENCE missing field: {field}")
            else:
                self.pass_(f"API_REFERENCE documents {field}")

    def check_project_overview(self) -> None:
        """检查项目入口文档是否记录关键架构。"""

        overview = self.read_text("docs/PROJECT_OVERVIEW.md")
        required_terms = [
            "Phase 11",
            "File Upload Pipeline",
            "Docs Runtime Verification",
            "PDF",
            "DOCX",
            "TXT",
            "MD",
            "CSV",
            "Dense + Keyword",
            "Reranker",
            "Phase 12",
            "Task Reliability",
            "task_events",
            "task_logs",
            "cancelled",
            "timeout",
            "Phase 13",
            "Tool Calling",
            "ToolRegistry",
            "builtin tools",
            "tool_call_logs",
            "Phase 14",
            "Memory Foundation",
            "conversation_sessions",
            "conversation_messages",
            "agent_memories",
            "memory_trace",
            "Phase 15",
            "Multi-Agent Foundation",
            "AgentRegistry",
            "agent_runs",
            "agent_messages",
            "agent_handoffs",
            "content_planner",
            "rag_agent",
            "ToolAgent",
            "fixed Agent Chain",
            "Phase 16",
            "Agent Planning Foundation",
            "SimplePlannerAgent",
            "plans",
            "plan_steps",
            "plan_reviews",
            "Plan Execution Flow",
            "Phase 17",
            "Browser Automation Adapter Foundation",
            "BrowserProvider",
            "MockBrowserProvider",
            "PlaywrightBrowserProvider",
            "browser_sessions",
            "browser_actions",
            "browser_action_logs",
            "browser_tool",
            "Phase 18",
            "Playwright Local Provider Integration",
            "PlaywrightLocalProvider",
            "playwright_local",
            "Screenshot System",
            "screenshot_path",
            "get_page_content",
            "Phase 19",
            "Remote Browser Worker Foundation",
            "RemoteBrowserProvider",
            "BrowserWorkerClient",
            "browser_workers",
            "browser_worker_sessions",
            "browser_worker_actions",
            "Worker Registration",
            "Worker Heartbeat",
            "Worker Runtime Mock",
            "Phase 20",
            "Real Browser Worker Service",
            "browser-worker",
            "worker/main.py",
            "worker/browser_worker/playwright_runtime.py",
            "API Server -> Worker",
            "http://browser-worker:9100",
            "Playwright Chromium",
            "worker/screenshots",
            "Phase 21",
            "Browser Worker Reliability",
            "BrowserWorkerHealthService",
            "BrowserWorkerSelector",
            "BrowserSessionCleanupService",
            "ScreenshotCleanupService",
            "max_sessions",
            "active_sessions",
            "least loaded worker",
            "stale worker",
            "action retry",
            "screenshot cleanup",
            "Phase 22",
            "Persistent Browser Profile Foundation",
            "BrowserProfileService",
            "browser_profiles",
            "profile_id",
            "profile_path",
            "persistent_context_enabled",
            "launch_persistent_context",
            "worker/profiles",
            "Profile Lock",
            "Profile Release",
            "Phase 23",
            "Browser Profile Health & Recovery",
            "BrowserProfileHealthService",
            "BrowserProfileBackupService",
            "BrowserProfileCleanupService",
            "browser_profile_usage_logs",
            "health_status",
            "usage_count",
            "profile backup",
            "stale lock recovery",
            "Phase 24",
            "Human-in-the-loop Browser Control",
            "BrowserHumanControlService",
            "browser_human_control_sessions",
            "browser_human_control_events",
            "session paused",
            "session resumed",
            "request_human_control",
            "complete_human_control",
            "Phase 25",
            "Browser Worker UI Access Placeholder",
            "BrowserUIAccessService",
            "browser_ui_access_sessions",
            "access token hash",
            "placeholder URL",
            "create_ui_access",
            "revoke_ui_access",
            "Phase 26",
            "Browser Worker Security & Access Control",
            "BrowserWorkerAuthService",
            "BrowserActionPolicyService",
            "browser_security_audit_logs",
            "worker_secret_hash",
            "signed worker request",
            "UI Access Scope",
            "Browser Action Policy",
            "Phase 27",
            "Customer Machine Worker Bootstrap",
            "worker_client",
            "worker_config.example.yaml",
            "worker_config.yaml",
            "worker_state.json",
            "python -m worker_client.cli register",
            "python -m worker_client.cli heartbeat",
            "python -m worker_client.cli serve",
            "python -m worker_client.cli start",
            "customer machine",
            "registration flow",
            "heartbeat flow",
            "local worker runtime",
            "Phase 28",
            "OpenClaw Worker Adapter Foundation",
            "worker_client/openclaw",
            "BaseOpenClawProvider",
            "MockOpenClawProvider",
            "OpenClawRuntime",
            "OpenClawWorkerClient",
            "openclaw_tool",
            "openclaw_action_logs",
            "OPENCLAW_PROVIDER",
            "OPENCLAW_ENABLED",
            "OPENCLAW_ACTION_TIMEOUT_SECONDS",
            "Phase 29",
            "Worker Client Packaging & Worker Console Foundation",
            "Worker Runtime Manager",
            "worker_client/runtime_manager.py",
            "worker_client/status.py",
            "worker_client/logging.py",
            "worker_client/local_api_client.py",
            "worker_client/runtime_state/status.json",
            "worker_client/logs/worker.log",
            "GET /local/status",
            "GET /local/health",
            "POST /local/runtime/start",
            "POST /local/runtime/stop",
            "POST /local/runtime/restart",
            "POST /local/heartbeat/start",
            "POST /local/heartbeat/stop",
            "GET /local/logs",
            "Packaging Scripts",
            "packaging/windows_start_worker.ps1",
            "packaging/mac_start_worker.sh",
            "Worker Console Foundation",
            "Desktop Runtime Placeholder",
            "no GUI",
            "Phase 30",
            "Worker Console GUI Foundation",
            "worker_console",
            "Vite",
            "React",
            "TypeScript",
            "Tailwind",
            "localWorkerClient.ts",
            "VITE_LOCAL_WORKER_API",
            "http://127.0.0.1:9100",
            "Runtime Control",
            "Worker API unreachable",
            "no exe / dmg",
            "no system tray",
            "Phase 31",
            "Worker Console Desktop App Foundation",
            "worker_console_desktop",
            "Tauri",
            "src-tauri/tauri.conf.json",
            "npm run tauri dev",
            "http://127.0.0.1:9100/local/status",
            "Worker Runtime 未启动",
            "no auto update",
            "Phase 32",
            "Worker Console System Tray & Desktop Runtime Foundation",
            "System Tray",
            "Minimize To Tray",
            "Tray Runtime Control",
            "Desktop Status Sync",
            "AutoStart Placeholder",
            "settings.example.json",
            "minimizeToTray",
            "refreshIntervalMs",
            "minimize_to_tray",
            "Show Console",
            "Hide Window",
            "Refresh Status",
            "Quit",
            "no formal installer",
            "no auto-update",
            "remote shell",
            "arbitrary command execution",
            "Phase 33",
            "Conversation Runtime Foundation",
            "conversation_threads",
            "conversation_events",
            "ConversationService",
            "run_conversation_turn",
            "message_received",
            "planning_started",
            "tool_called",
            "worker_action_started",
            "assistant_response",
            "Chat Panel Foundation",
            "Event Timeline",
            "polling",
            "WebSocket",
            "SSE",
            "Phase 34",
            "Remote Browser Runtime Foundation",
            "browser_runtime_sessions",
            "BrowserRuntimeSessionService",
            "app/browser/providers/remote_provider.py",
            "worker_client/browser_runtime",
            "Browser Session Lifecycle",
            "storage/browser_screenshots",
            "Browser Sessions Panel",
            "playwright install chromium",
            "Phase 35A",
            "Browser Runtime Observability & Replay",
            "browser_runtime_events",
            "browser_runtime_snapshots",
            "browser_runtime_replays",
            "BrowserRuntimeObservabilityService",
            "Timeline Event Flow",
            "Snapshot Storage",
            "Replay Metadata Flow",
            "Failure Debug",
            "metadata-only replay",
            "not live stream",
            "not VNC",
            "not noVNC",
            "not DevTools",
            "Phase 35B",
            "Real Client Worker E2E Validation Plan",
            "validate_real_client_worker_e2e.py",
            "expected_worker_name",
            "SKIPPED",
            "real client worker not online",
            "Swagger validation flow",
            "Worker Console validation checklist",
            "do not expose port 9100 to the public internet",
            "Tailscale",
            "VPN",
            "Phase 36",
            "Admin Dashboard Foundation",
            "admin_dashboard",
            "VITE_AI_SERVER_API",
            "VITE_WORKSPACE_ID",
            "VITE_USER_ID",
            "workersApi",
            "browserRuntimeApi",
            "conversationsApi",
            "tasksApi",
            "openclawApi",
            "auditApi",
            "ragApi",
            "Overview",
            "Workers",
            "Browser Runtime",
            "Audit Logs",
            "RAG / Documents",
            "Settings",
            "read-only monitoring foundation",
            "no login UI",
            "no permission UI",
            "no publishing business flow",
            "no real social platform control",
            "Phase 37",
            "Conversation Runtime Frontend Integration",
            "Admin Dashboard Conversation page",
            "Worker Console Chat Panel",
            "Desktop Chat Panel",
            "Polling Event Timeline",
            "CORS_ALLOWED_ORIGINS",
            "not WebSocket",
            "not SSE",
            "not a full ChatGPT UI",
            "Phase 38",
            "Conversation Runtime Tool Execution Bridge",
            "ConversationToolRouter",
            "Tool Execution Bridge",
            "Routing Rules",
            "Browser Bridge Flow",
            "OpenClaw Mock Bridge Flow",
            "RAG bridge",
            "Content bridge",
            "Planning bridge",
            "route_selected",
            "tool_execution_started",
            "tool_execution_completed",
            "agent_execution_started",
            "planning_execution_started",
            "route_name",
            "selected_tool",
            "result_metadata",
            "not autonomous agent",
            "Phase 39",
            "Conversation Execution Review & Approval Flow",
            "conversation_approvals",
            "ConversationApprovalService",
            "ConversationRiskPolicy",
            "review_first",
            "auto_safe",
            "execute_after_approval",
            "approval events",
            "pending approvals panel",
            "Tool Execution Gate",
            "not a full permission system",
            "Phase 40",
            "Conversation Execution Templates & Playbooks",
            "conversation_playbooks",
            "conversation_playbook_runs",
            "ConversationPlaybookService",
            "ConversationPlaybookExecutor",
            "browser_screenshot_report",
            "content_generation",
            "Playbook Runs",
            "Step Timeline",
            "Approval integration",
            "not a full workflow builder",
            "Phase 41",
            "Playbook Run Artifacts & Output Library",
            "output_artifacts",
            "OutputArtifactService",
            "Output Library",
            "content_draft",
            "rag_answer",
            "Export markdown",
            "not a full DAM",
            "S3",
            "MinIO",
            "Phase 42",
            "Task Orchestration & Background Execution",
            "task_runs",
            "task_run_events",
            "TaskOrchestratorService",
            "BackgroundTaskExecutor",
            "TaskRetryPolicy",
            "Background Execution",
            "Scheduled Tasks",
            "Approval resume",
            "Artifact linkage",
            "not Celery",
            "not Kubernetes",
            "not production HA",
            "Phase 43",
            "Task Scheduler Persistence & Worker Recovery",
            "task_scheduler_state",
            "TaskRecoveryService",
            "Task Lease",
            "Scheduler Health",
            "Failed Diagnostics",
            "stuck task recovery",
            "expired lease",
            "Phase 44",
            "Output Artifact Pipeline & Export System",
            "Artifact lineage",
            "artifact_relationships",
            "ArtifactExportService",
            "ArtifactPackagingService",
            "ArtifactRetentionService",
            "Artifact Explorer",
            "not a full DAM",
            "production object storage platform",
        ]
        for term in required_terms:
            if term not in overview:
                self.error(f"PROJECT_OVERVIEW.md missing term: {term}")
            else:
                self.pass_(f"PROJECT_OVERVIEW documents {term}")

    def check_phase_status(self) -> None:
        """检查中英文状态文档是否声明最新 Phase。"""

        zh_status = self.read_text("docs/zh/PROJECT_STATUS.md")
        en_status = self.read_text("docs/en/PROJECT_STATUS.md")
        for name, text in (("zh", zh_status), ("en", en_status)):
            if not re.search(r"Phase\s+35A", text):
                self.error(f"{name}/PROJECT_STATUS.md missing Phase 35A")
            elif "Browser Runtime Observability & Replay" not in text or "browser_runtime_events" not in text:
                self.error(f"{name}/PROJECT_STATUS.md does not describe Phase 35A scope")
            elif not re.search(r"Phase\s+35B", text):
                self.error(f"{name}/PROJECT_STATUS.md missing Phase 35B")
            elif (
                "Real Client Worker E2E Validation Plan" not in text
                or "validate_real_client_worker_e2e.py" not in text
                or "SKIPPED" not in text
            ):
                self.error(f"{name}/PROJECT_STATUS.md does not describe Phase 35B scope")
            elif not re.search(r"Phase\s+36", text):
                self.error(f"{name}/PROJECT_STATUS.md missing Phase 36")
            elif (
                "Admin Dashboard Foundation" not in text
                or "admin_dashboard" not in text
                or "VITE_AI_SERVER_API" not in text
                or "read-only monitoring foundation" not in text
            ):
                self.error(f"{name}/PROJECT_STATUS.md does not describe Phase 36 scope")
            elif not re.search(r"Phase\s+37", text):
                self.error(f"{name}/PROJECT_STATUS.md missing Phase 37")
            elif (
                "Conversation Runtime Frontend Integration" not in text
                or "Admin Dashboard Conversation page" not in text
                or "Worker Console Chat Panel" not in text
                or "Polling Event Timeline" not in text
                or "not WebSocket" not in text
                or "not SSE" not in text
            ):
                self.error(f"{name}/PROJECT_STATUS.md does not describe Phase 37 scope")
            elif not re.search(r"Phase\s+38", text):
                self.error(f"{name}/PROJECT_STATUS.md missing Phase 38")
            elif (
                "Conversation Runtime Tool Execution Bridge" not in text
                or "ConversationToolRouter" not in text
                or "route_selected" not in text
                or "tool_execution_started" not in text
                or "result_metadata" not in text
                or "not autonomous agent" not in text
            ):
                self.error(f"{name}/PROJECT_STATUS.md does not describe Phase 38 scope")
            elif not re.search(r"Phase\s+39", text):
                self.error(f"{name}/PROJECT_STATUS.md missing Phase 39")
            elif (
                "Conversation Execution Review & Approval Flow" not in text
                or "conversation_approvals" not in text
                or "ConversationApprovalService" not in text
                or "ConversationRiskPolicy" not in text
                or "review_first" not in text
                or "execute_after_approval" not in text
                or "not a full permission system" not in text
            ):
                self.error(f"{name}/PROJECT_STATUS.md does not describe Phase 39 scope")
            elif not re.search(r"Phase\s+40", text):
                self.error(f"{name}/PROJECT_STATUS.md missing Phase 40")
            elif (
                "Conversation Execution Templates & Playbooks" not in text
                or "conversation_playbooks" not in text
                or "conversation_playbook_runs" not in text
                or "ConversationPlaybookService" not in text
                or "ConversationPlaybookExecutor" not in text
                or "not a full workflow builder" not in text
            ):
                self.error(f"{name}/PROJECT_STATUS.md does not describe Phase 40 scope")
            elif not re.search(r"Phase\s+41", text):
                self.error(f"{name}/PROJECT_STATUS.md missing Phase 41")
            elif (
                "Playbook Run Artifacts & Output Library" not in text
                or "output_artifacts" not in text
                or "OutputArtifactService" not in text
                or "Output Library" not in text
                or "not a full DAM" not in text
            ):
                self.error(f"{name}/PROJECT_STATUS.md does not describe Phase 41 scope")
            elif not re.search(r"Phase\s+42", text):
                self.error(f"{name}/PROJECT_STATUS.md missing Phase 42")
            elif (
                "Task Orchestration & Background Execution" not in text
                or "task_runs" not in text
                or "task_run_events" not in text
                or "TaskOrchestratorService" not in text
                or "BackgroundTaskExecutor" not in text
                or "TaskRetryPolicy" not in text
                or "execution_mode" not in text
                or "not Celery" not in text
                or "not Kubernetes" not in text
            ):
                self.error(f"{name}/PROJECT_STATUS.md does not describe Phase 42 scope")
            elif not re.search(r"Phase\s+43", text):
                self.error(f"{name}/PROJECT_STATUS.md missing Phase 43")
            elif (
                "Task Scheduler Persistence & Worker Recovery" not in text
                or "task_scheduler_state" not in text
                or "TaskRecoveryService" not in text
                or "Task Lease" not in text
                or "Scheduler Health" not in text
                or "Failed Diagnostics" not in text
                or "not Celery" not in text
                or "not Kubernetes" not in text
                or "not production HA" not in text
            ):
                self.error(f"{name}/PROJECT_STATUS.md does not describe Phase 43 scope")
            elif not re.search(r"Phase\s+44", text):
                self.error(f"{name}/PROJECT_STATUS.md missing Phase 44")
            elif (
                "Output Artifact Pipeline & Export System" not in text
                or "Artifact lineage" not in text
                or "artifact_relationships" not in text
                or "ArtifactExportService" not in text
                or "ArtifactPackagingService" not in text
                or "ArtifactRetentionService" not in text
                or "Artifact Explorer" not in text
                or "not a full DAM" not in text
                or "production object storage platform" not in text
            ):
                self.error(f"{name}/PROJECT_STATUS.md does not describe Phase 44 scope")
            else:
                self.pass_(f"{name}/PROJECT_STATUS documents Phase 35A, Phase 35B, Phase 36, Phase 37, Phase 38, Phase 39, Phase 40, Phase 41, Phase 42, Phase 43, and Phase 44")

    def print_results(self) -> None:
        """输出 PASS / WARNING / ERROR。"""

        for result in self.results:
            print(f"{result.level}: {result.message}")
        errors = sum(1 for result in self.results if result.level == "ERROR")
        warnings = sum(1 for result in self.results if result.level == "WARNING")
        if errors:
            print(f"SUMMARY: ERROR ({errors} errors, {warnings} warnings)")
        elif warnings:
            print(f"SUMMARY: WARNING ({warnings} warnings)")
        else:
            print("SUMMARY: PASS")


def main(argv: Iterable[str] | None = None) -> int:
    """命令行入口。"""

    _ = list(argv or [])
    return DocsRuntimeVerifier(ROOT).run()


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
